# -----------------------------------------------
# Eureka Server - Application Configuration
# -----------------------------------------------

# Unique application name for discovery clients
spring.application.name=eureka-server

# Port for the Eureka Server
server.port=8761

# -----------------------------------------------
# Config Server Import
# -----------------------------------------------
# Import external configuration from Spring Cloud Config Server.
# This URI is passed via ENV variable CONFIGSERVER_URI, fallback to localhost for local test.
spring.config.import=optional:configserver:${CONFIGSERVER_URI:http://localhost:8888}

# -----------------------------------------------
# Eureka Standalone Mode
# -----------------------------------------------

# Do not register the Eureka Server to itself
eureka.client.register-with-eureka=false

# Do not fetch registry from other Eureka Servers
eureka.client.fetch-registry=false

# Default zone used by Eureka clients
# Uses ENV variable EUREKA_DEFAULT_ZONE, fallback to localhost.
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

# Explicit hostname for the Eureka instance
eureka.instance.hostname=eureka-server

# Disable auto registration for Spring Cloud Service Registry (not needed for Eureka server)
spring.cloud.service-registry.auto-registration.enabled=false
