server.port=8085

# Mongo db
spring.data.mongodb.uri=mongodb://dev:dev@match-event-db:27017/match-event
spring.data.mongodb.database=match-event

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated

# match event queue
match-event.queue.name=match-event-queue
match-event.exchange.name=match.event.exchange
match-event.routing.key=match.event

logging.level.root=DEBUG

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
