server.port=${SERVER_PORT:8084}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://dev:dev@pattern-detector-sequence-db:27017/pattern-detector-sequence}
spring.data.mongodb.database=${MONGODB_DATABASE:pattern-detector-sequence}

# Redis
spring.redis.host=${REDIS_HOST:pattern-detector-sequence-redis}
spring.redis.port=${REDIS_PORT:6379}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
spring.rabbitmq.publisher-confirm-type=${RABBITMQ_CONFIRM_TYPE:correlated}

# Queues and Exchanges
keystroke.queue.name=${KEYSTROKE_QUEUE:keystroke-queue}
match-event.queue.name=${MATCH_EVENT_QUEUE:match-event-queue}
match-event.exchange.name=${MATCH_EVENT_EXCHANGE:match.event.exchange}
match-event.routing.key=${MATCH_EVENT_ROUTING_KEY:match.event}

# Logging
logging.level.root=${LOG_LEVEL:DEBUG}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URI:http://eureka-server:8761/eureka}
