server.port=8083

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URI}

spring.cloud.config.fail-fast=true

eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.hostname}:${random.value}
eureka.instance.prefer-ip-address=true
