apiVersion: v1
kind: Service
metadata:
  name: keystroke-db
  namespace: pattern-matcher-system
spec:
  type: ClusterIP
  selector:
    app: keystroke-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432 