apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keystroke-postgres-pvc
  namespace: pattern-matcher-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 