apiVersion: v1
kind: Service
metadata:
  name: keystroke-service
  namespace: pattern-matcher-system
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082 
