apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: pattern-matcher-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
        - name: session-service
          image: christiandenisi/session-service:dev
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: session-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
