apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-db
  namespace: pattern-matcher-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-db
  template:
    metadata:
      labels:
        app: session-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "dev"
            - name: POSTGRES_PASSWORD
              value: "dev"
            - name: POSTGRES_DB
              value: "session_db"
          volumeMounts:
            - name: session-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: session-db-storage
          persistentVolumeClaim:
            claimName: session-db-pvc
