apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: pattern-matcher-system
spec:
  type: ClusterIP
  selector:
    app: session-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
