apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-config
  namespace: pattern-matcher-system
data:
  CONFIGSERVER_URI: "http://config-server.pattern-matcher-system.svc.cluster.local:8888"
  EUREKA_DEFAULT_ZONE: "http://eureka-server.pattern-matcher-system.svc.cluster.local:8761/eureka"
  SPRING_PROFILES_ACTIVE: "default"
  WAIT_FOR_IT: "false"
