spring.application.name=eureka-server

# Use environment variable or fallback to local default for Config Server
spring.config.import=optional:configserver:${CONFIGSERVER_URI:http://localhost:8888}

# Active profile (native or git, decided by env)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
