apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pattern-matcher-system

resources:
  - namespace.yaml
  - config-server/
  - eureka-server/
  - session-service/
  - keystroke-service/
  - rabbitmq-server/
